# Diccionario con las coordenadas geográficas (latitud, longitud) de las capitales de cada departamento
DEPARTAMENTOS = {
    "Amazonas": {"lat": -6.2294, "lng": -77.8726},
    "Ancash": {"lat": -9.5278, "lng": -77.5278},
    "Apurimac": {"lat": -13.6339, "lng": -72.8814},
    "Arequipa": {"lat": -16.4090, "lng": -71.5375},
    "Ayacucho": {"lat": -13.1588, "lng": -74.2239},
    "Cajamarca": {"lat": -7.1638, "lng": -78.5003},
    "Callao": {"lat": -12.0566, "lng": -77.1181},
    "Cusco": {"lat": -13.5320, "lng": -71.9675},
    "Huancavelica": {"lat": -12.7826, "lng": -74.9727},
    "Huanuco": {"lat": -9.9306, "lng": -76.2422},
    "Ica": {"lat": -14.0678, "lng": -75.7286},
    "Junin": {"lat": -12.0651, "lng": -75.2049},
    "La Libertad": {"lat": -8.1091, "lng": -79.0215},
    "Lambayeque": {"lat": -6.7714, "lng": -79.8409},
    "Lima": {"lat": -12.0464, "lng": -77.0428},
    "Loreto": {"lat": -3.7491, "lng": -73.2538},
    "Madre de Dios": {"lat": -12.5933, "lng": -69.1836},
    "Moquegua": {"lat": -17.1950, "lng": -70.9357},
    "Pasco": {"lat": -10.6675, "lng": -76.2567},
    "Piura": {"lat": -5.1945, "lng": -80.6328},
    "Puno": {"lat": -15.8402, "lng": -70.0219},
    "San Martin": {"lat": -6.0333, "lng": -76.9667},
    "Tacna": {"lat": -18.0066, "lng": -70.2463},
    "Tumbes": {"lat": -3.5669, "lng": -80.4515},
    "Ucayali": {"lat": -8.3791, "lng": -74.5539}
}

# Lista de adyacencias (fronteras terrestres entre departamentos)
ADYACENCIAS = {
    "Amazonas": ["Loreto", "San Martin", "La Libertad", "Cajamarca"],
    "Ancash": ["La Libertad", "Huanuco", "Lima"],
    "Apurimac": ["Ayacucho", "Cusco", "Arequipa"],
    "Arequipa": ["Ica", "Ayacucho", "Apurimac", "Cusco", "Puno", "Moquegua"],
    "Ayacucho": ["Ica", "Huancavelica", "Junin", "Cusco", "Apurimac", "Arequipa"],
    "Cajamarca": ["Piura", "Lambayeque", "La Libertad", "Amazonas"],
    "Callao": ["Lima"],
    "Cusco": ["Junin", "Ucayali", "Madre de Dios", "Puno", "Arequipa", "Apurimac", "Ayacucho"],
    "Huancavelica": ["Lima", "Ica", "Ayacucho", "Junin"],
    "Huanuco": ["La Libertad", "San Martin", "Loreto", "Ucayali", "Pasco", "Lima", "Ancash"],
    "Ica": ["Lima", "Huancavelica", "Ayacucho", "Arequipa"],
    "Junin": ["Lima", "Pasco", "Ucayali", "Cusco", "Ayacucho", "Huancavelica"],
    "La Libertad": ["Lambayeque", "Cajamarca", "Amazonas", "San Martin", "Huanuco", "Ancash"],
    "Lambayeque": ["Piura", "Cajamarca", "La Libertad"],
    "Lima": ["Ancash", "Huanuco", "Pasco", "Junin", "Huancavelica", "Ica", "Callao"],
    "Loreto": ["Amazonas", "San Martin", "Huanuco", "Ucayali"],
    "Madre de Dios": ["Ucayali", "Cusco", "Puno"],
    "Moquegua": ["Arequipa", "Puno", "Tacna"],
    "Pasco": ["Huanuco", "Ucayali", "Junin", "Lima"],
    "Piura": ["Tumbes", "Cajamarca", "Lambayeque"],
    "Puno": ["Madre de Dios", "Cusco", "Arequipa", "Moquegua", "Tacna"],
    "San Martin": ["Loreto", "Amazonas", "La Libertad", "Huanuco"],
    "Tacna": ["Moquegua", "Puno"],
    "Tumbes": ["Piura"],
    "Ucayali": ["Loreto", "Huanuco", "Pasco", "Junin", "Cusco", "Madre de Dios"]
}
